config/routes.rb
Moviedb::Application.routes.draw do
  get "home/index"

  resources :movies do
    get 'random', on: :collection
    resources :actors
    resources :genres
    resources :views
    resources :directors
  end
  
  resources :directors
  resources :actors
  resources :genres
  resources :views

  root :to => 'home#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  
  validates :name, :presence => true
  
  has_many :genres_movies, :dependent => :destroy
  has_many :movies, :through => :genres_movies
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.order(:name)
    
    if params[:q]
      @genres.keep_if {|genre| genre.name =~ Regexp.new(Regexp.escape(params[:q]))}
    end
    
    @search = params[:q] || ""

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end
  
  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |genre_form| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation" class="ui-widget ui-state-error ui-corner-all" style="padding: 0 .7em;">
      <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;">&nbsp;</span>
      <strong><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</strong>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= genre_form.label :name, 'Name:' %>
  	<%= genre_form.text_field :name %>
  </div>
  
  <div class="actions">
    <%= genre_form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<%= content_for :title do %>
	Editing <%= @genre.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Show', @genre %>
<% end %>

<article class="genre">
	<%= render 'form' %>
</article>

app/views/genres/index.html.erb
<%= content_for :title do %>
	Genres
<% end %>

<%= content_for :options do %>
	<%= link_to 'New Genre', new_genre_path %>
<% end %>

<form action="" method="GET" role="search" onsubmit="return q.value != ''">
	<input id="searchbar" type="text" name="q" placeholder="Search..." <% if defined? @search %>value="<%= @search %>"<% end %> />
	<button title="Search" id="searchbtn" type="submit" class="ui-button-icon-only"><span style="display: inline-block" class="ui-icon ui-icon-search"></span></button>
</form>

<% @genres.each do |genre| %>
	<article class="genre">
		<a href="<%= url_for genre %>"><h2><%= genre.name %></h2></a>
		<%= link_to 'Edit', edit_genre_path(genre), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
		<%= link_to 'Destroy', genre, method: :delete, data: { confirm: "Do you want to permanently delete the genre #{genre.name}" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
	</article>
<% end %>

app/views/genres/new.html.erb
<%= content_for :title do %>
	New genre
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
<% end %>

<article class="genre">
	<%= render 'form' %>
</article>

app/views/genres/show.html.erb
<%= content_for :title do %>
	<%= @genre.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Edit', edit_genre_path(@genre) %>
	<%= link_to 'Destroy', @genre, method: :delete, data: { confirm: "Do you want to permanently delete the genre #{@genre.name}?" } %>
<% end %>

<p id="notice"><%= notice %></p>

<article class="genre">
	<h2><%= @genre.name %></h2>
	
    <% @genre.movies.sort! { |a,b| a.title.downcase <=> b.title.downcase } %>
	<% @genre.movies.each do |movie| %>
		<article class="<%= movie.dvd == 1 ? "dvd" : "video" %>">
			<a href="<%= url_for movie %>"><h2><%= movie.display_name %> <%= movie.yearstring %></h2></a>
			<%= link_to 'Edit', edit_movie_path(movie), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
			<%= link_to 'Delete', movie, method: :delete, data: { confirm: "Do you want to permanently delete the movie #{movie.display_name}?" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
			<% if movie.lastWatched %>
				<p>Last Watched: <span class="lastwatched"><%= movie.lastWatched %></span></p>
			<% end %>
			<p>Duration: <span><%= movie.duration %><% if movie.duration %> minutes<% end %></span></p>
			<div>
			<% movie.actors.each do |actor| %>
				<%= link_to actor.name, actor %><% if actor != movie.actors.last %>, <% end %>
			<% end %>
			</div>
		</article>
	<% end %>
</article>