config/routes.rb
Moviedb::Application.routes.draw do
  get "home/index"

  resources :movies do
    get 'random', on: :collection
    resources :actors
    resources :genres
    resources :views
    resources :directors
  end
  
  resources :directors
  resources :actors
  resources :genres
  resources :views

  root :to => 'home#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :firstname, :lastname
  
  validates :lastname, :presence => true
  
  has_many :actors_movies, :dependent => :destroy
  has_many :movies, :through => :actors_movies
  
  # Outputs the actor's name in the format 'firstname lastname'
  def name
    "#{firstname} #{lastname}"
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.order(:lastname, :firstname)
    
    if params[:q]
      @actors.keep_if {|actor| actor.name =~ Regexp.new(Regexp.escape(params[:q]))}
    end
    
    @search = params[:q] || ""

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end
  
  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |actor_form| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation" class="ui-widget ui-state-error ui-corner-all" style="padding: 0 .7em;">
      <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;">&nbsp;</span>
      <strong><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</strong>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= actor_form.label :firstname, 'First Name:' %>
  	<%= actor_form.text_field :firstname %>
  </div>
  <div class="field">
  	<%= actor_form.label :lastname, 'Last Name:' %>
  	<%= actor_form.text_field :lastname %>
  </div>
  
  <div class="actions">
    <%= actor_form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<%= content_for :title do %>
	Editing <%= @actor.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Show', @actor %>
<% end %>

<article class="person">
	<%= render 'form' %>
</article>

app/views/actors/index.html.erb
<%= content_for :title do %>
	Actors
<% end %>

<%= content_for :options do %>
	<%= link_to 'New Actor', new_actor_path %>
<% end %>

<form action="" method="GET" role="search" onsubmit="return q.value != ''">
	<input id="searchbar" type="text" name="q" placeholder="Search..." <% if defined? @search %>value="<%= @search %>"<% end %> />
	<button title="Search" id="searchbtn" type="submit" class="ui-button-icon-only"><span style="display: inline-block" class="ui-icon ui-icon-search"></span></button>
</form>
<% @actors.each do |actor| %>
		<article class="person">
			<a href="<%= url_for actor %>"><h2><%= actor.name %></h2></a>
			<%= link_to 'Edit', edit_actor_path(actor), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
			<%= link_to 'Destroy', actor, method: :delete, data: { confirm: "Do you want to permanently delete the actor #{actor.name}?" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
		</article>
<% end %>

app/views/actors/new.html.erb
<%= content_for :title do %>
	New actor
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
<% end %>

<article class="person">
	<%= render 'form' %>
</article>

app/views/actors/show.html.erb
<%= content_for :title do %>
	<%= @actor.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Edit', edit_actor_path(@actor) %>
	<%= link_to 'Delete', @actor, method: :delete, data: { confirm: "Do you want to permanently delete the actor #{@actor.name}?" } %>
<% end %>

<p id="notice"><%= notice %></p>

<article class="person">
	<h2><%= @actor.name %></h2>
	
    <% @actor.movies.sort! { |a,b| a.title.downcase <=> b.title.downcase } %>
	<% @actor.movies.each do |movie| %>
		<article class="<%= movie.dvd == 1 ? "dvd" : "video" %>">
			<a href="<%= url_for movie %>"><h2><%= movie.display_name %> <%= movie.yearstring %></h2></a>
			<%= link_to 'Edit', edit_movie_path(movie), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
			<%= link_to 'Delete', movie, method: :delete, data: { confirm: "Do you want to permanently delete the movie #{movie.display_name}?" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
			<% if movie.lastWatched %>
				<p>Last Watched: <span class="lastwatched"><%= movie.lastWatched %></span></p>
			<% end %>
			<p>Duration: <span><%= movie.duration %><% if movie.duration %> minutes<% end %></span></p>
			<div>
			<% movie.genres.each do |genre| %>
				<%= link_to genre.name, genre, :class => "genre" %>
			<% end %>
			</div>
		</article>
	<% end %>
</article>