config/routes.rb
Moviedb::Application.routes.draw do
  get "home/index"

  resources :movies do
    get 'random', on: :collection
    resources :actors
    resources :genres
    resources :views
    resources :directors
  end
  
  resources :directors
  resources :actors
  resources :genres
  resources :views

  root :to => 'home#index'

end

app/models/director.rb
class Director < ActiveRecord::Base
  attr_accessible :firstname, :lastname
  
  validates :lastname, :presence => true
  
  has_many :directors_movies, :dependent => :destroy
  has_many :movies, :through => :directors_movies
  
  # Outputs the director's name in the format 'firstname lastname'
  def name
    "#{firstname} #{lastname}"
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.order(:lastname, :firstname)
    
    if params[:q]
      @directors.keep_if {|director| director.name =~ Regexp.new(Regexp.escape(params[:q]))}
    end
    
    @search = params[:q] || ""

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end
  
  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render json: @director, status: :created, location: @director }
      else
        format.html { render action: "new" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |director_form| %>
  <% if @director.errors.any? %>
    <div id="error_explanation" class="ui-widget ui-state-error ui-corner-all" style="padding: 0 .7em;">
      <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;">&nbsp;</span>
      <strong><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</strong>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= director_form.label :firstname, 'First Name:' %>
  	<%= director_form.text_field :firstname %>
  </div>
  <div class="field">
  	<%= director_form.label :lastname, 'Last Name:' %>
  	<%= director_form.text_field :lastname %>
  </div>
  
  <div class="actions">
    <%= director_form.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<%= content_for :title do %>
	Editing <%= @director.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Show', @director %>
<% end %>

<article class="person">
	<%= render 'form' %>
</article>

app/views/directors/index.html.erb
<%= content_for :title do %>
	Directors
<% end %>

<%= content_for :options do %>
	<%= link_to 'New Director', new_director_path %>
<% end %>

<form action="" method="GET" role="search" onsubmit="return q.value != ''">
	<input id="searchbar" type="text" name="q" placeholder="Search..." <% if defined? @search %>value="<%= @search %>"<% end %> />
	<button title="Search" id="searchbtn" type="submit" class="ui-button-icon-only"><span style="display: inline-block" class="ui-icon ui-icon-search"></span></button>
</form>
<% @directors.each do |director| %>
		<article class="person">
			<a href="<%= url_for director %>"><h2><%= director.name %></h2></a>
			<%= link_to 'Edit', edit_director_path(director), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
			<%= link_to 'Destroy', director, method: :delete, data: { confirm: "Do you want to permanently delete the director #{director.name}?" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
		</article>
<% end %>

app/views/directors/new.html.erb
<%= content_for :title do %>
	New director
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
<% end %>

<article class="person">
	<%= render 'form' %>
</article>

app/views/directors/show.html.erb
<%= content_for :title do %>
	<%= @director.name %>
<% end %>

<%= content_for :options do %>
	<%= link_to 'Back', back_url %>
	<%= link_to 'Edit', edit_director_path(@director) %>
	<%= link_to 'Delete', @director, method: :delete, data: { confirm: "Do you want to permanently delete the director #{@director.name}?" } %>
<% end %>

<p id="notice"><%= notice %></p>

<article class="person">
	<h2><%= @director.name %></h2>
	
    <% @director.movies.sort! { |a,b| a.title.downcase <=> b.title.downcase } %>
	<% @director.movies.each do |movie| %>
		<article class="<%= movie.dvd == 1 ? "dvd" : "video" %>">
			<a href="<%= url_for movie %>"><h2><%= movie.display_name %> <%= movie.yearstring %></h2></a>
			<%= link_to 'Edit', edit_movie_path(movie), :class => "btn-edit ui-icon ui-icon-pencil", :title => 'Edit' %>
			<%= link_to 'Delete', movie, method: :delete, data: { confirm: "Do you want to permanently delete the movie #{movie.display_name}?" }, :class => "btn-delete ui-icon ui-icon-closethick", :title => 'Delete' %>
			<% if movie.lastWatched %>
				<p>Last Watched: <span class="lastwatched"><%= movie.lastWatched %></span></p>
			<% end %>
			<p>Duration: <span><%= movie.duration %><% if movie.duration %> minutes<% end %></span></p>
			<div>
			<% movie.genres.each do |genre| %>
				<%= link_to genre.name, genre, :class => "genre" %>
			<% end %>
			</div>
		</article>
	<% end %>
</article>