config/routes.rb
Moviedb::Application.routes.draw do
  get "home/index"

  resources :movies do
    get 'random', on: :collection
    resources :actors
    resources :genres
    resources :views
    resources :directors
  end
  
  resources :directors
  resources :actors
  resources :genres
  resources :views

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= controller_name.capitalize %> | Home Movie Database</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

<hgroup>
	<a href="<%= root_path %>"><h1>Home Movie Database</h1></a>
	<nav role="navigation">
		<%= link_to "Movies", movies_path %>
		<%= link_to "Actors", actors_path %>
		<%= link_to "Genres", genres_path %>
		<%= link_to "Views", views_path %>
		<%= link_to "Directors", directors_path %>
		<%= link_to "Random", random_movies_path %>
	</nav>
</hgroup>

<section id="content">
	<h1><%= yield :title %></h1>
	<div class="optionsarea">
		<%= yield :options %>
	</div>
	<div class="mainarea">
	<%= yield %>
	</div>
</section>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home | Home Movie Database</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

<hgroup>
	<h1>Home Movie Database</h1>
	<nav role="navigation">
		<%= link_to "Movies", movies_path %>
		<%= link_to "Actors", actors_path %>
		<%= link_to "Genres", genres_path %>
		<%= link_to "Views", views_path %>
		<%= link_to "Directors", directors_path %>
		<%= link_to "Random", random_movies_path %>
	</nav>
</hgroup>

<section id="center-content">
<%= yield %>
</section>

</body>
</html>